In [29]:
#Step 1.1

import re
import pandas as pd

file_path = 'fraudulent_emails.txt'

data = []

from_pattern = re.compile(r'^From:\s*["\']?\s*((?i:dr\.?)\b[^<"\n]+?)\s*["\']?\s*<([a-zA-Z0-9._%+-]+@([a-zA-Z0-9.-]+\.(?:com|net)))>',re.MULTILINE,)

with open(file_path, 'r', encoding='latin-1') as f:
    for line_num, line in enumerate(f, start=1):
        match = from_pattern.match(line)
        if match:
            name = match.group(1).strip()
            email = match.group(2).strip()
            domain = match.group(3).strip()
            data.append({'Line Number': line_num,'Name': name,'E-mail Address': email,'E-mail Domain': domain,})

df = pd.DataFrame(data)

print('Total matched records:',len(df))
df.head(21)

Total matched records: 144

,Line Number,Name,E-mail Address,E-mail Domain
0,747,Dr.Sam jordan,sjordan@diplomats.com,diplomats.com
1,1118,DR. ANAYO AWKA,anayoawka@hotmail.com,hotmail.com
2,1156,DR. ANAYO AWKA,anayoawka@hotmail.com,hotmail.com
3,2068,DR. JAMES ALBERT,jamesalbert0@eircom.net,eircom.net
4,3838,DR. SANNI SABO,davidmensoh@mail.com,mail.com
5,3920,DR. SANNI SABO,davidmensoh@mail.com,mail.com
6,4861,DR. SANNI SABO,davidmensoh@mail.com,mail.com
7,4920,Dr Luisa Pimental Estrada,luisaestrada2002@luisapestrada.zzn.com,luisapestrada.zzn.com
8,5625,DR. BELLO MUSA,dr_bellomusa01@omaninfo.com,omaninfo.com
9,7290,Dr mariam abacha,marabac011@hotmail.com,hotmail.com
10,8401,DR DOUGLAS NWANKWO,douglankwo@yahoo.com,yahoo.com
11,9169,Dr Mariam abacha,mariam.aba@caramail.com,caramail.com
12,9225,Dr.Moses,moses1970@englishexpert.com,englishexpert.com
13,9276,Dr.Moses,moses1970@englishexpert.com,englishexpert.com
14,9327,DR. OLUSEGUN SMITH,olu002@phantomemail.com,phantomemail.com
15,9417,Dr. Bernard Makelele,benkelele@phantomemail.com,phantomemail.com
16,9878,DR ABDULL RASAQ,drabdullrasaq@phantomemail.com,phantomemail.com
17,10035,DR ABDULL RASAQ,drabdullrasaq@phantomemail.com,phantomemail.com
18,11363,Dr. Don Arturo Ramitez.,don_1000@fastermail.com,fastermail.com
19,12463,DR STEPHEN UMAH,u.stephen1@caramail.com,caramail.com
20,12560,Dr stephen umah,u.stephen@caramail.com,caramail.com

In [30]:
#Step 1.2

import re
import pandas as pd

date_pattern = re.compile(r"^Date:\s*(?:([A-Za-z]{3}),\s*)?(\d{1,2}\s+[A-Za-z]{3}\s+\d{4})\s+(\d{2}:\d{2}:\d{2})")

data = []

with open(file_path, 'r', encoding='latin-1') as f:
    lines = f.readlines()

for line_idx, line in enumerate(lines):
    from_match = from_pattern.match(line)
    if from_match:
        line_num = line_idx + 1
        name = from_match.group(1).strip()
        email = from_match.group(2).strip()
        domain = from_match.group(3).strip()

        day, date_val, time_val = None, None, None

        start_idx = max(0, line_idx - 6)
        end_idx = min(len(lines), line_idx + 7)

        for nearby_idx in range(start_idx, end_idx):
            date_match = date_pattern.match(lines[nearby_idx])
            if date_match:
                day = date_match.group(1) if date_match.group(1) else ''
                date_val = date_match.group(2)
                time_val = date_match.group(3)
                break

        data.append({'Line Number': line_num,'Name': name,'E-mail Address': email,'E-mail Domain': domain,'Day': day,'Date': date_val,'Time': time_val,})

df = pd.DataFrame(data)

df_options = df[['Name','E-mail Address','E-mail Domain','Day','Date','Time','Line Number',]]

df_options

,Name,E-mail Address,E-mail Domain,Day,Date,Time,Line Number
0,Dr.Sam jordan,sjordan@diplomats.com,diplomats.com,Fri,08 Nov 2002,04:15:33,747
1,DR. ANAYO AWKA,anayoawka@hotmail.com,hotmail.com,Fri,15 Nov 2002,00:40:13,1118
2,DR. ANAYO AWKA,anayoawka@hotmail.com,hotmail.com,Fri,15 Nov 2002,01:18:50,1156
3,DR. JAMES ALBERT,jamesalbert0@eircom.net,eircom.net,Tue,26 Nov 2002,04:34:05,2068
4,DR. SANNI SABO,davidmensoh@mail.com,mail.com,Fri,1 Jan 1999,22:08:55,3838
...,...,...,...,...,...,...,...
139,Dr johnson Agu,dr_johnson12@yahoo.com,yahoo.com,None,None,None,311267
140,Dr johnson Agu,dr_johnson12@yahoo.com,yahoo.com,None,None,None,311317
141,DR AHMED SHALAA,drahmed_sh14@hotmail.com,hotmail.com,Wed,27 Jun 2007,16:31:06,316748
142,Dr. Ahmed Hassan,ahassan1696@gmail.com,gmail.com,Sun,22 Jul 2007,15:03:36,322055
143,Dr. Ahmed Hassan,ahassan1696@gmail.com,gmail.com,Sun,22 Jul 2007,15:03:36,322135

In [31]:
#Question 1

df_final.head(21)

,Name,E-mail Address,E-mail Domain,Day,Date,Time,Line Number
0,Dr.Sam jordan,sjordan@diplomats.com,diplomats.com,Fri,08 Nov 2002,04:15:33,747
1,DR. ANAYO AWKA,anayoawka@hotmail.com,hotmail.com,Fri,15 Nov 2002,00:40:13,1118
2,DR. ANAYO AWKA,anayoawka@hotmail.com,hotmail.com,Fri,15 Nov 2002,01:18:50,1156
3,DR. JAMES ALBERT,jamesalbert0@eircom.net,eircom.net,Tue,26 Nov 2002,04:34:05,2068
4,DR. SANNI SABO,davidmensoh@mail.com,mail.com,Fri,1 Jan 1999,22:08:55,3838
5,DR. SANNI SABO,davidmensoh@mail.com,mail.com,Sat,2 Jan 1999,01:43:13,3920
6,DR. SANNI SABO,davidmensoh@mail.com,mail.com,Fri,1 Jan 1999,11:44:49,4861
7,Dr Luisa Pimental Estrada,luisaestrada2002@luisapestrada.zzn.com,luisapestrada.zzn.com,Sat,18 Jan 2003,15:49:19,4920
8,DR. BELLO MUSA,dr_bellomusa01@omaninfo.com,omaninfo.com,Thu,23 Jan 2003,04:16:53,5625
9,Dr mariam abacha,marabac011@hotmail.com,hotmail.com,Fri,7 Feb 2003,17:38:37,7290
10,DR DOUGLAS NWANKWO,douglankwo@yahoo.com,yahoo.com,Sun,16 Feb 2003,03:52:27,8401
11,Dr Mariam abacha,mariam.aba@caramail.com,caramail.com,Fri,21 Feb 2003,16:26:31,9169
12,Dr.Moses,moses1970@englishexpert.com,englishexpert.com,Sat,22 Feb 2003,00:58:13,9225
13,Dr.Moses,moses1970@englishexpert.com,englishexpert.com,Sat,22 Feb 2003,01:00:30,9276
14,DR. OLUSEGUN SMITH,olu002@phantomemail.com,phantomemail.com,Sat,22 Feb 2003,16:13:44,9327
15,Dr. Bernard Makelele,benkelele@phantomemail.com,phantomemail.com,Sun,23 Feb 2003,01:00:06,9417
16,DR ABDULL RASAQ,drabdullrasaq@phantomemail.com,phantomemail.com,Thu,27 Feb 2003,14:01:47,9878
17,DR ABDULL RASAQ,drabdullrasaq@phantomemail.com,phantomemail.com,Thu,27 Feb 2003,14:28:58,10035
18,Dr. Don Arturo Ramitez.,don_1000@fastermail.com,fastermail.com,Fri,1 Jan 1999,22:39:02,11363
19,DR STEPHEN UMAH,u.stephen1@caramail.com,caramail.com,Sat,22 Mar 2003,05:09:19,12463
20,Dr stephen umah,u.stephen@caramail.com,caramail.com,Fri,4 Oct 2002,00:08:46,12560

In [32]:
#Question 2

days, dates, times = [], [], []

for line_num in df['Line Number']:
    line_idx = line_num - 1
    start_idx = max(0, line_idx - 5)
    end_idx = min(len(lines), line_idx + 6)

    day_val, date_val, time_val = None, None, None

    for nearby_idx in range(start_idx, end_idx):
        date_match = date_pattern.match(lines[nearby_idx])
        if date_match:
            day_val = date_match.group(1) if date_match.group(1) else ""
            date_val = date_match.group(2)
            time_val = date_match.group(3)
            break

    days.append(day_val)
    dates.append(date_val)
    times.append(time_val)

df['Day'] = days
df['Date'] = dates
df['Time'] = times

df_q2 = df[['Name', 'E-mail Address', 'E-mail Domain', 'Day', 'Date', 'Time']]

df_q2.head(21)

,Name,E-mail Address,E-mail Domain,Day,Date,Time
0,Dr.Sam jordan,sjordan@diplomats.com,diplomats.com,Fri,08 Nov 2002,04:15:33
1,DR. ANAYO AWKA,anayoawka@hotmail.com,hotmail.com,Fri,15 Nov 2002,00:40:13
2,DR. ANAYO AWKA,anayoawka@hotmail.com,hotmail.com,Fri,15 Nov 2002,01:18:50
3,DR. JAMES ALBERT,jamesalbert0@eircom.net,eircom.net,Tue,26 Nov 2002,04:34:05
4,DR. SANNI SABO,davidmensoh@mail.com,mail.com,Fri,1 Jan 1999,22:08:55
5,DR. SANNI SABO,davidmensoh@mail.com,mail.com,Sat,2 Jan 1999,01:43:13
6,DR. SANNI SABO,davidmensoh@mail.com,mail.com,Fri,1 Jan 1999,11:44:49
7,Dr Luisa Pimental Estrada,luisaestrada2002@luisapestrada.zzn.com,luisapestrada.zzn.com,Sat,18 Jan 2003,15:49:19
8,DR. BELLO MUSA,dr_bellomusa01@omaninfo.com,omaninfo.com,Thu,23 Jan 2003,04:16:53
9,Dr mariam abacha,marabac011@hotmail.com,hotmail.com,Fri,7 Feb 2003,17:38:37
10,DR DOUGLAS NWANKWO,douglankwo@yahoo.com,yahoo.com,Sun,16 Feb 2003,03:52:27
11,Dr Mariam abacha,mariam.aba@caramail.com,caramail.com,Fri,21 Feb 2003,16:26:31
12,Dr.Moses,moses1970@englishexpert.com,englishexpert.com,Sat,22 Feb 2003,00:58:13
13,Dr.Moses,moses1970@englishexpert.com,englishexpert.com,Sat,22 Feb 2003,01:00:30
14,DR. OLUSEGUN SMITH,olu002@phantomemail.com,phantomemail.com,Sat,22 Feb 2003,16:13:44
15,Dr. Bernard Makelele,benkelele@phantomemail.com,phantomemail.com,Sun,23 Feb 2003,01:00:06
16,DR ABDULL RASAQ,drabdullrasaq@phantomemail.com,phantomemail.com,Thu,27 Feb 2003,14:01:47
17,DR ABDULL RASAQ,drabdullrasaq@phantomemail.com,phantomemail.com,Thu,27 Feb 2003,14:28:58
18,Dr. Don Arturo Ramitez.,don_1000@fastermail.com,fastermail.com,Fri,1 Jan 1999,22:39:02
19,DR STEPHEN UMAH,u.stephen1@caramail.com,caramail.com,Sat,22 Mar 2003,05:09:19
20,Dr stephen umah,u.stephen@caramail.com,caramail.com,Fri,4 Oct 2002,00:08:46